import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ProductProjectFileStore } from "../src/product/projects/project-store.js";
import { ProductProjectService } from "../src/product/projects/project-service.js";
import { KeywordMonitorStore } from "../src/product/keyword-monitor-store.js";
import { KeywordMonitorService } from "../src/product/keyword-monitor-service.js";
import type { KeywordMonitorRun } from "../src/product/keyword-monitor-schema.js";
test("keyword diff compares recommendations, positions and sources", async()=>{const root=await mkdtemp(join(tmpdir(),"niubigeo-diff-"));try{const projectStore=new ProductProjectFileStore(root);const projects=new ProductProjectService(projectStore);const project=await projects.createDraft({primaryDomain:"diff.example"});const store=new KeywordMonitorStore(projectStore);const service=new KeywordMonitorService(projects,store);const monitor=await service.create(project.id,{keyword:"best tools"});const base={monitorId:monitor.id,projectId:project.id,keyword:monitor.keyword,status:"completed" as const,mentioned:[],positions:{}};const old:KeywordMonitorRun={...base,id:"old",startedAt:"2026-10-01T00:00:00Z",modelResults:[{modelId:"m",modelName:"Model",answer:"",mentioned:[],recommended:["A"],position:2,citations:["https://a.example"]}]};const latest:KeywordMonitorRun={...base,id:"latest",startedAt:"2026-10-02T00:00:00Z",modelResults:[{modelId:"m",modelName:"Model",answer:"",mentioned:[],recommended:["B"],position:0,citations:["https://b.example"]}]};await store.saveRun(old);await store.saveRun(latest);const diff=await service.diff(project.id,monitor.id);assert.deepEqual(diff?.addedRecommendations,["B"]);assert.deepEqual(diff?.removedRecommendations,["A"]);assert.deepEqual(diff?.addedSources,["https://b.example"]);assert.equal(diff?.movedMentions[0]?.from,2);assert.equal(diff?.movedMentions[0]?.to,0);assert.equal(diff?.hasChanges,true)}finally{await rm(root,{recursive:true,force:true})}});

test("keyword diff ignores failed model snapshots without reporting removals", async()=>{const root=await mkdtemp(join(tmpdir(),"niubigeo-diff-failure-"));try{const projectStore=new ProductProjectFileStore(root);const projects=new ProductProjectService(projectStore);const project=await projects.createDraft({primaryDomain:"failure.example"});const store=new KeywordMonitorStore(projectStore);const service=new KeywordMonitorService(projects,store);const monitor=await service.create(project.id,{keyword:"best tools"});const base={monitorId:monitor.id,projectId:project.id,keyword:monitor.keyword,status:"completed" as const,mentioned:[],positions:{}};await store.saveRun({...base,id:"old",startedAt:"2026-10-01T00:00:00Z",modelResults:[{modelId:"m",modelName:"Model",answer:"A",mentioned:["A"],recommended:["A"],position:0,citations:["https://a.example"]}]});await store.saveRun({...base,id:"latest",startedAt:"2026-10-02T00:00:00Z",modelResults:[{modelId:"m",modelName:"Model",answer:"",mentioned:[],recommended:[],position:null,citations:[],error:"provider failed"}]});const diff=await service.diff(project.id,monitor.id);assert.deepEqual(diff?.addedRecommendations,[]);assert.deepEqual(diff?.removedRecommendations,[]);assert.deepEqual(diff?.movedMentions,[]);assert.deepEqual(diff?.addedSources,[]);assert.deepEqual(diff?.removedSources,[]);assert.equal(diff?.hasChanges,false)}finally{await rm(root,{recursive:true,force:true})}});

test("keyword monitors are independent, customizable and template-backed", async()=>{const root=await mkdtemp(join(tmpdir(),"niubigeo-keywords-"));try{const projects=new ProductProjectService(new ProductProjectFileStore(root));const project=await projects.createDraft({primaryDomain:"example.com",brandName:"牛逼GEO",aliases:["NiubiGEO"]});const service=new KeywordMonitorService(projects,new KeywordMonitorStore(new ProductProjectFileStore(root)));const templates=service.templates();assert.ok(templates.some(t=>t.id==="ai-coding"));const rows=await service.createBatch(project.id,{keywords:["best AI coding agent","best AI coding agent","best Cursor alternatives"],frequency:"weekly",brandName:"牛逼GEO",aliases:["NiubiGEO"]});assert.equal(rows.length,2);assert.equal(rows[0]?.frequency,"weekly");assert.equal(rows[0]?.brandName,"牛逼GEO");assert.deepEqual(rows[0]?.aliases,["NiubiGEO"]);const other=await projects.createDraft({primaryDomain:"other.example"});assert.deepEqual(await service.list(other.id),[]);assert.equal((await service.runs(project.id,rows[0]?.id)).length,0);await service.update(project.id,rows[0]!.id,{frequency:"hourly",enabled:false});assert.equal((await service.list(project.id)).find(item=>item.id===rows[0]?.id)?.enabled,false)}finally{await rm(root,{recursive:true,force:true})}});
