import { randomUUID } from "node:crypto";
import { KEYWORD_MONITOR_TEMPLATES, type KeywordMonitor, type KeywordMonitorDiff, type KeywordMonitorFrequency, type KeywordMonitorKind, type KeywordMonitorRun } from "./keyword-monitor-schema.js";
import type { ProductProjectService } from "./projects/project-service.js";
import type { ProductBaselineService } from "./configuration/baseline-service.js";
import type { RecognitionAnswerExecutor } from "./recognition/recognition-service.js";
import { keywordDiscoveryPrompt, KEYWORD_DISCOVERY_SCHEMA_NAME, KEYWORD_DISCOVERY_TOOL_DESCRIPTION, keywordDiscoveryResponseSchema } from "./measurements/keyword-discovery-protocol.js";
import { KeywordMonitorStore } from "./keyword-monitor-store.js";
const now=()=>new Date().toISOString();
const normalize=(v:string)=>v.trim().split(" ").filter(Boolean).join(" ").toLocaleLowerCase();
const valid=(v:string)=>v.trim().length>=2&&v.trim().length<=240;
const languageFor=(value:string):"zh"|"en"|"pt-BR"=>value.toLocaleLowerCase().startsWith("pt")?"pt-BR":value.toLocaleLowerCase().startsWith("zh")?"zh":"en";
function structured(value:unknown):{mentions?:Array<{name?:unknown;recommendation?:unknown}>}|null{if(typeof value!=="string")return null;try{const parsed=JSON.parse(value) as unknown;return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as {mentions?:Array<{name?:unknown;recommendation?:unknown}>}:null}catch{return null}}
function ranking(value:unknown,names:string[]):number|null{const mentions=structured(value)?.mentions||[];const positive=mentions.filter(item=>item.recommendation==="positive"&&typeof item.name==="string");const wanted=new Set(names.map(normalize));const index=positive.findIndex(item=>wanted.has(normalize(item.name as string)));return index<0?null:index;}
function next(f:KeywordMonitorFrequency,from=new Date()){const d=new Date(from);if(f==="hourly")d.setHours(d.getHours()+1);else if(f==="daily")d.setDate(d.getDate()+1);else d.setDate(d.getDate()+7);return d.toISOString()}
export class KeywordMonitorService {
 constructor(private readonly projects:ProductProjectService,private readonly store:KeywordMonitorStore,private readonly baselines?:ProductBaselineService,private readonly executor?:RecognitionAnswerExecutor){}
 async list(projectId:string){await this.projects.get(projectId);return this.store.listMonitors(projectId)}
 async runs(projectId:string,monitorId?:string){await this.projects.get(projectId);return this.store.listRuns(projectId,monitorId)}
 templates(){return KEYWORD_MONITOR_TEMPLATES}
 async create(projectId:string,input:{keyword:string;kind?:KeywordMonitorKind;frequency?:KeywordMonitorFrequency;brandName?:string;aliases?:string[]}){await this.projects.get(projectId);if(!valid(input.keyword))throw new Error("关键词需要 2 到 240 个字符。");const frequency=input.frequency||"daily";if(!["hourly","daily","weekly"].includes(frequency))throw new Error("关键词监控频率无效。");const created=now();const v:KeywordMonitor={id:`keyword-monitor-${randomUUID()}`,projectId,keyword:input.keyword.trim(),normalizedKeyword:normalize(input.keyword),kind:input.kind||"discovery",frequency,enabled:true,aliases:[...(input.aliases||[])].map(v=>v.trim()).filter(Boolean),createdAt:created,updatedAt:created,nextRunAt:next(frequency),...(input.brandName?.trim()?{brandName:input.brandName.trim()}: {})};await this.store.saveMonitor(v);return v}
 async createBatch(projectId:string,input:{keywords:string[];kind?:KeywordMonitorKind;frequency?:KeywordMonitorFrequency;brandName?:string;aliases?:string[]}){const out=[];const seen=new Set<string>();for(const keyword of input.keywords){const n=normalize(keyword);if(!seen.has(n)){seen.add(n);out.push(await this.create(projectId,{...input,keyword}))}}return out}
 async diff(projectId:string,id:string):Promise<KeywordMonitorDiff|null>{const rows=await this.store.listRuns(projectId,id);if(rows.length<2)return null;const previous=rows[1]!,latest=rows[0]!;const successful=(row:NonNullable<KeywordMonitorRun["modelResults"]>[number])=>!row.error;const previousModels=new Map((previous.modelResults||[]).filter(successful).map(v=>[v.modelId,v]));const latestModels=new Map((latest.modelResults||[]).filter(successful).map(v=>[v.modelId,v]));const comparable=new Set([...previousModels.keys()].filter(modelId=>latestModels.has(modelId)));const previousRecommendations=[...new Set([...comparable].flatMap(modelId=>previousModels.get(modelId)?.recommended||[]))];const latestRecommendations=[...new Set([...comparable].flatMap(modelId=>latestModels.get(modelId)?.recommended||[]))];const previousSources=[...new Set([...comparable].flatMap(modelId=>previousModels.get(modelId)?.citations||[]))];const latestSources=[...new Set([...comparable].flatMap(modelId=>latestModels.get(modelId)?.citations||[]))];const movedMentions=[...comparable].flatMap(modelId=>{const old=previousModels.get(modelId)!;const row=latestModels.get(modelId)!;return old.position!==row.position?[{modelId,modelName:row.modelName,from:old.position,to:row.position}]:[]});const result:KeywordMonitorDiff={monitorId:id,previousRunId:previous.id,latestRunId:latest.id,previousAt:previous.startedAt,latestAt:latest.startedAt,addedRecommendations:latestRecommendations.filter(v=>!previousRecommendations.includes(v)),removedRecommendations:previousRecommendations.filter(v=>!latestRecommendations.includes(v)),movedMentions,addedSources:latestSources.filter(v=>!previousSources.includes(v)),removedSources:previousSources.filter(v=>!latestSources.includes(v)),changedModels:movedMentions.length,hasChanges:false};result.hasChanges=Boolean(result.addedRecommendations.length||result.removedRecommendations.length||result.movedMentions.length||result.addedSources.length||result.removedSources.length);return result}
 async runDue(at=new Date()){const projects=await this.projects.list({includeArchived:false});const completed=[];for(const project of projects){for(const monitor of await this.store.listMonitors(project.id)){if(monitor.enabled&&monitor.nextRunAt&&Date.parse(monitor.nextRunAt)<=at.getTime())completed.push(await this.run(project.id,monitor.id));}}return completed}
 async run(projectId:string,id:string){const monitor=await this.store.getMonitor(projectId,id);if(!monitor)throw new Error("关键词监控不存在。");if(!this.baselines||!this.executor)throw new Error("关键词监控执行器未配置。");const project=await this.projects.get(projectId);if(!project.activeBaselineId)throw new Error("请先保存模型配置。");const baseline=await this.baselines.get(projectId,project.activeBaselineId);const startedAt=now();const runId=`keyword-run-${randomUUID()}`;const modelResults=[];for(const model of baseline.modelSnapshots){try{const answer=await this.executor.execute({baseline,modelSnapshot:model,prompt:keywordDiscoveryPrompt({keyword:monitor.keyword,language:languageFor(project.defaultLanguage)}),requestParameters:{model:model.modelId, maxTokens:1200,temperature:0,requireProviderParameters:model.providerId==="openrouter",webSearchEnabled:model.webSearchMode==="provider_native",webSearchMode:model.webSearchMode,structuredOutputTransport:"response_json_schema",responseSchemaName:KEYWORD_DISCOVERY_SCHEMA_NAME,responseSchemaHash:"keyword-monitor-v1"},structuredOutput:{name:KEYWORD_DISCOVERY_SCHEMA_NAME,description:KEYWORD_DISCOVERY_TOOL_DESCRIPTION,schema:keywordDiscoveryResponseSchema}});const names=[monitor.brandName,...monitor.aliases].filter((v):v is string=>Boolean(v));const lower=answer.text.toLocaleLowerCase();const mentioned=names.filter(name=>lower.includes(name.toLocaleLowerCase()));const parsed=structured(answer.structuredOutput?.value);const recommended=(parsed?.mentions||[]).filter(item=>item.recommendation==="positive"&&typeof item.name==="string").map(item=>item.name as string);modelResults.push({modelId:model.modelId,modelName:model.displayName,answer:answer.text,mentioned,recommended,position:ranking(answer.structuredOutput?.value,names),citations:answer.citations.map(c=>c.url)});}catch(error){modelResults.push({modelId:model.modelId,modelName:model.displayName,answer:"",mentioned:[],recommended:[],position:null,citations:[],error:error instanceof Error?error.message:String(error)})}}const all=[...new Set(modelResults.flatMap(v=>v.mentioned))];const status: "completed" | "failed" = modelResults.some(v=>v.answer) ? "completed" : "failed";const result={id:runId,monitorId:id,projectId,keyword:monitor.keyword,status,startedAt,completedAt:now(),answer:modelResults.map(v=>v.answer).filter(Boolean).join("\n\n"),mentioned:all,positions:Object.fromEntries(modelResults.map(v=>[v.modelId,v.position])),modelResults};await this.store.saveRun(result);await this.update(projectId,id,{enabled:monitor.enabled,lastRunAt:result.completedAt,nextRunAt:next(monitor.frequency,new Date(result.completedAt))} as never);return result}

 async update(projectId:string,id:string,input:Partial<Pick<KeywordMonitor,"frequency"|"enabled"|"brandName"|"aliases"|"kind"|"lastRunAt"|"nextRunAt">>){const v=await this.store.getMonitor(projectId,id);if(!v)throw new Error("关键词监控不存在。");const nextValue={...v,...input,updatedAt:now()};if(input.frequency)nextValue.nextRunAt=next(input.frequency);await this.store.saveMonitor(nextValue);return nextValue}
 async remove(projectId:string,id:string){if(!await this.store.deleteMonitor(projectId,id))throw new Error("关键词监控不存在。");return {deleted:true}}
}
